#!/usr/bin/env python3
"""Fail when a pull request's own commits or body carry tool attribution."""

import os
import subprocess
import sys

BANNED_SNIPPETS = (
    "generated by",
    "cursor agent",
    "cursoragent@",
    "co-authored-by: cursor",
    "co-authored-by: copilot",
    "co-authored-by: dependabot",
)


def violations(text):
    lowered = text.lower()
    return [snippet for snippet in BANNED_SNIPPETS if snippet in lowered]


def commit_text(base, head):
    log = subprocess.check_output(
        ["git", "log", f"{base}..{head}", "--format=%an%n%ae%n%B%n---END---"],
        text=True,
    )
    return log


def main(argv):
    if len(argv) != 3:
        print("usage: commit-hygiene.py <base-sha> <head-sha>", file=sys.stderr)
        return 2
    chunks = [commit_text(argv[1], argv[2]), os.environ.get("PR_BODY", "")]
    found = []
    for chunk in chunks:
        found.extend(violations(chunk))
    if found:
        print("commit hygiene failed:", ", ".join(sorted(set(found))))
        return 1
    print("commit hygiene ok")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
