#!/usr/bin/env python3
import importlib.util
import pathlib
import unittest

path = pathlib.Path(__file__).with_name("commit-hygiene.py")
spec = importlib.util.spec_from_file_location("commit_hygiene", path)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)


class HygieneTests(unittest.TestCase):
    def test_flags_tool_attribution(self):
        self.assertTrue(mod.violations("Co-authored-by: Cursor <cursoragent@cursor.com>"))
        self.assertTrue(mod.violations("Generated by a tool"))
        self.assertTrue(mod.violations("Author: Cursor Agent"))

    def test_allows_human_text(self):
        self.assertEqual(mod.violations("fix(api): reject a forged approver\n"), [])


if __name__ == "__main__":
    unittest.main()
